### ISSUE TITLE
Potentially unnecessary Python API

### ISSUE THREAD

**Issue by mrbuche** [autotwin/automesh#95]
@hovey should we reconsider some of the Python API? For example, the getter methods (nodal coordinates, element connectivity, etc.). They are not available from the CLI, and maybe the Python API should mimic the CLI? I realized when implementing the method to calculate the inverse connectivity in Rust, and stopped myself before implementing it in Python, since the user will likely not require this. Eliminating parts of the Python API will make it easier to maintain.

**Comment by hovey** [comment]
Hey @mrbuche thanks for that note.  For now, we could either (a) decrease the Python API to match the CLI, or (b) eliminate the Python API entirely.  Both options allow for better maintenance, since we don't have to duplicate effort.  

Let's move forward with the plan as you have stated above.  Thanks.  Chad

**Comment by mrbuche** [comment]
99
